<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="ozonetel-santosh" failures="5" tests="58" name="com.CA.qa.TestCases.ValidateOutboundCampaignPageTest" time="150.646" errors="0" timestamp="2021-01-27T13:56:49 IST" skipped="0">
  <testcase classname="com.CA.qa.TestCases.ValidateOutboundCampaignPageTest" name="ValidateCampaignNameErrorMsg26_1" time="0.156"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateOutboundCampaignPageTest" name="ValidateCampaignNameRangeErrorMsg26_12" time="0.188"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateOutboundCampaignPageTest" name="ValidateCampaignNameSplRangeErrorMsg26_13" time="0.187"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateOutboundCampaignPageTest" name="ValidateCampaignNameSplRangeErrorMsg26_14" time="0.170"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateOutboundCampaignPageTest" name="ValidateCampaignTypeErrorMsg26_2" time="0.100"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateOutboundCampaignPageTest" name="ValidateDidErrorMsg26_3" time="0.096"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateOutboundCampaignPageTest" name="ValidateDidRangeErrorMsg26_31" time="0.183">
    <failure message="expected [DID must be between 3 and 16 digits and allows the + prefix] but found [DID should be between 3 to 16 digits long and allows prefix +]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [DID must be between 3 and 16 digits and allows the + prefix] but found [DID should be between 3 to 16 digits long and allows prefix +]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.CA.qa.TestCases.ValidateOutboundCampaignPageTest.ValidateDidRangeErrorMsg26_31(ValidateOutboundCampaignPageTest.java:142)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- ValidateDidRangeErrorMsg26_31 -->
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateOutboundCampaignPageTest" name="ValidateDidRangeErrorMsg26_32" time="0.174">
    <failure message="expected [DID must be between 3 and 16 digits and allows the + prefix] but found [DID should be between 3 to 16 digits long and allows prefix +]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [DID must be between 3 and 16 digits and allows the + prefix] but found [DID should be between 3 to 16 digits long and allows prefix +]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.CA.qa.TestCases.ValidateOutboundCampaignPageTest.ValidateDidRangeErrorMsg26_32(ValidateOutboundCampaignPageTest.java:150)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- ValidateDidRangeErrorMsg26_32 -->
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateOutboundCampaignPageTest" name="ValidateDidRangeErrorMsg26_33" time="0.173">
    <failure message="expected [DID must be between 3 and 16 digits and allows the + prefix] but found [DID should be between 3 to 16 digits long and allows prefix +]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [DID must be between 3 and 16 digits and allows the + prefix] but found [DID should be between 3 to 16 digits long and allows prefix +]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.CA.qa.TestCases.ValidateOutboundCampaignPageTest.ValidateDidRangeErrorMsg26_33(ValidateOutboundCampaignPageTest.java:158)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- ValidateDidRangeErrorMsg26_33 -->
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateOutboundCampaignPageTest" name="ValidateDidRangeErrorMsg26_34" time="0.171">
    <failure message="expected [DID must be between 3 and 16 digits and allows the + prefix] but found [DID should be between 3 to 16 digits long and allows prefix +]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [DID must be between 3 and 16 digits and allows the + prefix] but found [DID should be between 3 to 16 digits long and allows prefix +]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.CA.qa.TestCases.ValidateOutboundCampaignPageTest.ValidateDidRangeErrorMsg26_34(ValidateOutboundCampaignPageTest.java:166)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- ValidateDidRangeErrorMsg26_34 -->
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateOutboundCampaignPageTest" name="ValidateDidRangeMaxErrorMsg" time="0.215">
    <failure message="expected [DID must be between 3 and 16 digits and allows the + prefix] but found [DID should be between 3 to 16 digits long and allows prefix +]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [DID must be between 3 and 16 digits and allows the + prefix] but found [DID should be between 3 to 16 digits long and allows prefix +]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.CA.qa.TestCases.ValidateOutboundCampaignPageTest.ValidateDidRangeMaxErrorMsg(ValidateOutboundCampaignPageTest.java:174)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- ValidateDidRangeMaxErrorMsg -->
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateOutboundCampaignPageTest" name="ValidateFallbackDidRangeMaxErrorMsg26_4" time="0.191"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateOutboundCampaignPageTest" name="ValidateFallbackDidRangeMaxErrorMsg26_41" time="0.169"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateOutboundCampaignPageTest" name="ValidateFallbackDidRangeMaxErrorMsg26_42" time="0.167"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateOutboundCampaignPageTest" name="ValidateFallbackDidRangeMaxErrorMsg26_43" time="0.166"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateOutboundCampaignPageTest" name="ValidateStartTimeErrorMsg26_5" time="0.092"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateOutboundCampaignPageTest" name="ValidateEndTimeErrorMsg26_51" time="0.103"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateOutboundCampaignPageTest" name="ValidateGreaterEndTimeErrorMsg26_52" time="0.358"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateOutboundCampaignPageTest" name="ValidatePriorityErrorMsg26_6" time="0.103"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateOutboundCampaignPageTest" name="ValidatePriorityRangeErrorMsg26_61" time="0.221"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateOutboundCampaignPageTest" name="ValidatePrefixRangeErrorMsg26_7" time="0.209"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateOutboundCampaignPageTest" name="ValidatePrefixRangeErrorMsg26_71" time="0.195"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateOutboundCampaignPageTest" name="ValidatePrefixRangeErrorMsg26_72" time="0.201"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateOutboundCampaignPageTest" name="ValidatePluginNameErrorMsg" time="0.265"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateOutboundCampaignPageTest" name="ValidateTriesErrorMsg26_8" time="0.106"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateOutboundCampaignPageTest" name="ValidateTriesRangeErrorMsg26_81" time="0.232"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateOutboundCampaignPageTest" name="ValidateTriesRangemaxErrorMsg26_82" time="0.203"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateOutboundCampaignPageTest" name="ValidateBlockNoEmptyErrorMsg26_9" time="0.197"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateOutboundCampaignPageTest" name="ValidateWrapupErrorMsg26_10" time="0.091"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateOutboundCampaignPageTest" name="ValidateDispositionErrorMsg26_111" time="0.095"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateOutboundCampaignPageTest" name="ValidateSkillErrorMsg26_121" time="0.095"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateOutboundCampaignPageTest" name="ValidateMapErrorMsg26_131" time="0.116"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateOutboundCampaignPageTest" name="ValidateUploadErrorMsg26_141" time="0.101"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateOutboundCampaignPageTest" name="ValidateCustomerRingTimeEmptyErrorMsg26_151" time="0.247"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateOutboundCampaignPageTest" name="ValidateCustomerRingTimeRangeErrorMsg26_152" time="0.318"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateOutboundCampaignPageTest" name="ValidateCustomerRingTimeRangeMaxErrorMsg26_153" time="0.302"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateOutboundCampaignPageTest" name="ValidateAppUrlEmptyErrorMsg26_16_1" time="0.201"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateOutboundCampaignPageTest" name="ValidateAppUrlInvalidErrorMsg26_16_2" time="0.291"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateOutboundCampaignPageTest" name="ValidateConcurrentCallsEmptyErrorMsg26_17_1" time="0.205"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateOutboundCampaignPageTest" name="ValidateConcurrentCallsRangeErrorMsg26_17_2" time="0.324"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateOutboundCampaignPageTest" name="ValidatePacingRatioEmptyErrorMsg26_18_1" time="3.367"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateOutboundCampaignPageTest" name="ValidatePacingRatioInvalidErrorMsg26_18_2" time="0.320"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateOutboundCampaignPageTest" name="ValidatePacingRatioInvalidErrorMsg26_18_3" time="0.318"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateOutboundCampaignPageTest" name="ValidatePacingRatioInvalidErrorMsg26_18_4" time="0.321"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateOutboundCampaignPageTest" name="ValidatePacingRatioInvalidErrorMsg26_18_5" time="0.307"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateOutboundCampaignPageTest" name="ValidateMaxDropRatioEmptyErrorMsg26_19_1" time="0.211"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateOutboundCampaignPageTest" name="ValidateMaxDropRatioRangeErrorMsg26_19_2" time="0.283"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateOutboundCampaignPageTest" name="ValidateDialIntervalErrorMsg26_201" time="0.239"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateOutboundCampaignPageTest" name="ValidateEmptyMapNameErrorMsg26_202" time="21.349"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateOutboundCampaignPageTest" name="ValidateMapNameRangeErrorMsg26_203" time="31.341"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateOutboundCampaignPageTest" name="ValidateMapNameSplRangeErrorMsg26_204" time="31.339"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateOutboundCampaignPageTest" name="ValidateMapFileErrorMsg26_205" time="21.286"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateOutboundCampaignPageTest" name="ValidateMapFileSampleTooltipMsg26_206" time="11.129"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateOutboundCampaignPageTest" name="ValidateMapFileXlsOnlyTooltipMsg26_207" time="11.224"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateOutboundCampaignPageTest" name="ValidateFileUploadSampleTooltipMsg26_208" time="0.026"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateOutboundCampaignPageTest" name="ValidateFileUploadXlsOnlyTooltipMsg26_209" time="0.027"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateOutboundCampaignPageTest" name="ValidateMappingTooltipMsg26_210" time="0.020"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateOutboundCampaignPageTest" name="ValidateConsolidatedErrMsg" time="10.162"/>
  <system-out/>
</testsuite> <!-- com.CA.qa.TestCases.ValidateOutboundCampaignPageTest -->
