<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="ozonetel-santosh" failures="4" tests="44" name="com.CA.qa.TestCases.ValidateCampaignPageTest" time="165.616" errors="0" timestamp="2021-01-04T13:25:19 IST" skipped="0">
  <testcase classname="com.CA.qa.TestCases.ValidateCampaignPageTest" name="ValidateCampaignNameErrorMsg" time="0.259"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateCampaignPageTest" name="ValidateCampaignNameRangeErrorMsg" time="0.406"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateCampaignPageTest" name="ValidateCampaignNameSplRangeErrorMsg" time="0.341"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateCampaignPageTest" name="ValidateCampaignTypeErrorMsg" time="0.208"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateCampaignPageTest" name="ValidateDidErrorMsg" time="0.198"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateCampaignPageTest" name="ValidateDidRangeErrorMsg" time="0.363"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateCampaignPageTest" name="ValidateDidRangeMaxErrorMsg" time="0.417"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateCampaignPageTest" name="ValidateStartTimeErrorMsg" time="0.219"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateCampaignPageTest" name="ValidateEndTimeErrorMsg" time="0.220"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateCampaignPageTest" name="ValidateGreaterEndTimeErrorMsg" time="0.613"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateCampaignPageTest" name="ValidatePriorityErrorMsg" time="0.190"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateCampaignPageTest" name="ValidatePriorityRangeErrorMsg" time="0.395"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateCampaignPageTest" name="ValidatePluginNameErrorMsg" time="0.545"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateCampaignPageTest" name="ValidateTriesErrorMsg" time="0.221"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateCampaignPageTest" name="ValidateTriesRangeErrorMsg" time="0.454"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateCampaignPageTest" name="ValidateTriesRangemaxErrorMsg" time="0.389"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateCampaignPageTest" name="ValidateWrapupErrorMsg" time="0.229"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateCampaignPageTest" name="ValidateDispositionErrorMsg" time="0.205"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateCampaignPageTest" name="ValidateSkillErrorMsg" time="0.199"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateCampaignPageTest" name="ValidateMapErrorMsg" time="0.211"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateCampaignPageTest" name="ValidateUploadErrorMsg" time="0.217"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateCampaignPageTest" name="ValidateDialIntervalErrorMsg" time="0.464"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateCampaignPageTest" name="ValidateAppUrlEmptyErrorMsg" time="0.440"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateCampaignPageTest" name="ValidateAppUrlInvalidErrorMsg" time="0.559"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateCampaignPageTest" name="ValidateConcurrentCallsEmptyErrorMsg" time="0.431"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateCampaignPageTest" name="ValidateConcurrentCallsRangeErrorMsg" time="0.622">
    <failure message="expected [Max Concurrent Calls should be between 1 and 99.] but found [Max Concurrent Calls should be between 1 and 9999.]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Max Concurrent Calls should be between 1 and 99.] but found [Max Concurrent Calls should be between 1 and 9999.]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.CA.qa.TestCases.ValidateCampaignPageTest.ValidateConcurrentCallsRangeErrorMsg(ValidateCampaignPageTest.java:302)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- ValidateConcurrentCallsRangeErrorMsg -->
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateCampaignPageTest" name="ValidateConcurrentCallsMaxRangeErrorMsg" time="10.543">
    <failure message="expected [Max Concurrent Calls should be between 1 and 99.] but found []" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Max Concurrent Calls should be between 1 and 99.] but found []
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.CA.qa.TestCases.ValidateCampaignPageTest.ValidateConcurrentCallsMaxRangeErrorMsg(ValidateCampaignPageTest.java:312)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- ValidateConcurrentCallsMaxRangeErrorMsg -->
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateCampaignPageTest" name="ValidateCustomerRingTimeEmptyErrorMsg" time="0.416"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateCampaignPageTest" name="ValidateCustomerRingTimeRangeErrorMsg" time="0.585"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateCampaignPageTest" name="ValidateCustomerRingTimeRangeMaxErrorMsg" time="0.558"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateCampaignPageTest" name="ValidatePacingRatioEmptyErrorMsg" time="3.663"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateCampaignPageTest" name="ValidatePacingRatioInvalidErrorMsg" time="0.594"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateCampaignPageTest" name="ValidateMaxDropRatioEmptyErrorMsg" time="0.345"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateCampaignPageTest" name="ValidateMaxDropRatioRangeErrorMsg" time="0.549"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateCampaignPageTest" name="ValidateEmptyMapNameErrorMsg" time="21.516"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateCampaignPageTest" name="ValidateMapNameRangeErrorMsg" time="31.773">
    <failure message="expected [Map Name should be between 2 to 50 characters.] but found [Map Name should be between 2 to 50 alphanumeric characters long and allows special characters like _]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Map Name should be between 2 to 50 characters.] but found [Map Name should be between 2 to 50 alphanumeric characters long and allows special characters like _]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.CA.qa.TestCases.ValidateCampaignPageTest.ValidateMapNameRangeErrorMsg(ValidateCampaignPageTest.java:407)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- ValidateMapNameRangeErrorMsg -->
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateCampaignPageTest" name="ValidateMapNameSplRangeErrorMsg" time="31.572">
    <failure message="expected [Map Name allows alphanumeric characters with Underscore] but found [Map Name should be between 2 to 50 alphanumeric characters long and allows special characters like _]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Map Name allows alphanumeric characters with Underscore] but found [Map Name should be between 2 to 50 alphanumeric characters long and allows special characters like _]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.CA.qa.TestCases.ValidateCampaignPageTest.ValidateMapNameSplRangeErrorMsg(ValidateCampaignPageTest.java:418)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- ValidateMapNameSplRangeErrorMsg -->
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateCampaignPageTest" name="ValidateMapFileErrorMsg" time="21.465"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateCampaignPageTest" name="ValidateMapFileSampleTooltipMsg" time="11.337"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateCampaignPageTest" name="ValidateMapFileXlsOnlyTooltipMsg" time="11.409"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateCampaignPageTest" name="ValidateFileUploadSampleTooltipMsg" time="0.031"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateCampaignPageTest" name="ValidateFileUploadXlsOnlyTooltipMsg" time="0.031"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateCampaignPageTest" name="ValidateMappingTooltipMsg" time="0.029"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateCampaignPageTest" name="ValidateConsolidatedErrMsg" time="10.185"/>
  <system-out/>
</testsuite> <!-- com.CA.qa.TestCases.ValidateCampaignPageTest -->
